#!/usr/bin/env bash
# Updates and installs Nginx.
# Nginx listens on port 80 and serves a page returning a Hello World string.

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Starts nginx service
sudo service nginx start

# Allows nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Gives the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backs up default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creates new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restarts nginx
sudo service nginx restart

echo -e "\nCompleted. ✅\n"

