#!/usr/bin/env bash
# Script that installs Nginx server, redirects /redirect_me, and customizes 404 not found page.

# Updates package repository lists
sudo apt-get -y update

# Installs Nginx server
sudo apt-get -y install nginx

# Allows Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Creates a custom 404 not found page with the message "Ceci n'est pas une page"
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

# Configures Nginx to serve the custom 404 page
newlines="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "27i $newlines" /etc/nginx/sites-available/default

# Restarts the Nginx service to apply changes
sudo service nginx restart
