#!/usr/bin/env bash
# Installs and configures the load balancer (HAProxy).

echo -e "Updating and performing minor checks...\n"

function install() {
	command -v "$1" &> /dev/null

	# Shellcheck disable=SC2181
	if [ $? -ne 0 ]; then
		echo -e "    Installing: $1\n"
		sudo apt-get update -y -qq && \
			sudo apt-get install -y "$1" -qq
		echo -e "\n"
	else
		echo -e "    ${1} is already installed.\n"
	fi
}

install haproxy # Install HAProxy

echo -e "\nSetting up some minor stuff.\n"

# Backup default server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config="
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend vnbnb-tech-frontend
    bind *:80
    default_backend vnbnb-tech-backend

backend vnbnb-tech-backend
    balance roundrobin
    server 530577-web-01 100.27.0.241:80 check
    server 530577-web-02 52.87.252.166:80 check
"

# Shellcheck disable=SC2154
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

echo "Configured - Roundrobin On web-01 & web-02"

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi
